var firstName = 'Bernadette';
var lastName = 'de Vera';
var age = 32;
var dateOfBirth = '06/11/1988';
var address = 'Winnipeg, Manitoba';
console.log(firstName);
console.log(lastName);
console.log(age);
console.log(dateOfBirth);
console.log(address);
